
spring:
  datasource:
    druid:
      url: jdbc:mysql://47.106.84.158:3306/fun_chat
      username: root
      password: Zp123...
      initial-size: 1
      min-idle: 1
      max-active: 20
      filters: stat,slf4j
      name: wms
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20